version: 0
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: 'relops-image-builder'
    extra:
      github:
        events:
          - pull_request.closed
          - push
    payload:
      maxRunTime: 3600
      command:
        - powershell -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/mozilla-platform-ops/relops-image-builder/{{event.head.sha}}/build_ami.ps1'))"
        #- git clone {{event.head.repo.url}} repo
        #- cd repo
        #- git config advice.detachedHead false
        #- git checkout {{event.head.sha}}
    metadata:
      name: iso-to-ami
      description: build windows ami from iso
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
allowPullRequests: collaborators