version: 0
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: 'relops-image-builder'
    extra:
      github:
        events:
          - pull_request.closed
          - push
    payload:
      maxRunTime: 3600
      command:
        - 'echo "run iso-to-ami on worker type: {{ taskcluster.docker.workerType }}"'
        #- /bin/bash
        #- '--login'
        #- '-c'
        #- >-
        #  git clone {{event.head.repo.url}} repo && cd repo && git config
        #  advice.detachedHead false && git checkout {{event.head.sha}} && echo
        #  "run iso-to-ami here on worker type: {{ taskcluster.docker.workerType }}"
    metadata:
      name: iso-to-ami
      description: build windows ami from iso
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
allowPullRequests: collaborators