version: 0
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: 'relops-image-builder'
    extra:
      github:
        events:
          - pull_request.closed
          - push
    payload:
      maxRunTime: 3600
      command:
        - 'echo "run iso-to-ami on worker type: {{ taskcluster.docker.workerType }}"'
        - git clone {{event.head.repo.url}} repo
        - cd repo
        - git config advice.detachedHead false
        - git checkout {{event.head.sha}}
        - dir
    metadata:
      name: iso-to-ami
      description: build windows ami from iso
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
allowPullRequests: collaborators