version: 0
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: 'relops-image-builder'
    extra:
      github:
        events:
          - pull_request.closed
          - push
    #os-groups:
    #  - Administrators
    scopes:
      - generic-worker:os-group:relops-image-builder/Administrators
    payload:
      maxRunTime: 3600
      command:
        - git clone {{event.head.repo.url}} relops-image-builder
        - git --git-dir=.\relops-image-builder\.git --work-tree=.\relops-image-builder config advice.detachedHead false
        - git --git-dir=.\relops-image-builder\.git --work-tree=.\relops-image-builder checkout {{event.head.sha}}
        - powershell -NoProfile -InputFormat None -ExecutionPolicy Bypass -File .\relops-image-builder\build_ami.ps1
    metadata:
      name: iso-to-ami
      description: build windows ami from iso
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
allowPullRequests: collaborators