version: 0
tasks:
  - provisionerId: '{{taskcluster.docker.provisionerId}}'
    routes:
      - 'index.project.releng.relops-image-builder.v1.revision.{{event.head.sha}}'
    workerType: '{{taskcluster.docker.workerType}}'
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
      data:
        base:
          sha: '{{event.base.sha}}'
          user:
            login: '{{event.base.user.login}}'
        head:
          sha: '{{event.head.sha}}'
          user:
            email: '{{event.head.user.email}}'
    payload:
      maxRunTime: 600
      image: 'grenade/opencloudconfig'
      features:
        taskclusterProxy: true
      command:
        - '/bin/bash'
        - '--login'
        - '-c'
        - 'git clone --quiet {{event.head.repo.url}}'
        - '&& git --git-dir=./relops-image-builder/.git --work-tree=./relops-image-builder fetch'
        - '&& git --git-dir=./relops-image-builder/.git --work-tree=./relops-image-builder checkout {{event.head.repo.branch}}'
        - '&& pip install taskcluster'
        - '&& python ./relops-image-builder/ci/decision-task.py'
    metadata:
      name: 'decision-task'
      description: 'Create CI tasks for the current commit'
      owner: '{{event.head.user.email}}'
      source: '{{event.head.repo.url}}'

  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: 'relops-image-builder'
    extra:
      github:
        events:
          - pull_request.closed
          - push
    scopes:
      - generic-worker:os-group:aws-provisioner-v1/relops-image-builder/Administrators
      - generic-worker:run-as-administrator:aws-provisioner-v1/relops-image-builder
    payload:
      osGroups:
        - Administrators
      maxRunTime: 3600
      command:
        - git clone {{event.head.repo.url}} relops-image-builder
        - git --git-dir=.\relops-image-builder\.git --work-tree=.\relops-image-builder config advice.detachedHead false
        - git --git-dir=.\relops-image-builder\.git --work-tree=.\relops-image-builder checkout {{event.head.sha}}
        - powershell -NoProfile -InputFormat None -File .\relops-image-builder\ci\iso-to-vhd.ps1
      features:
        runAsAdministrator: true
        taskclusterProxy: true
    metadata:
      name: iso-to-ami
      description: build windows ami from iso
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
allowPullRequests: collaborators